In [5]:
#List
import time as t

size = 1_000_000_00

list1 = list(range(size))
list2 = list(range(size))

start = t.time()
sum = [x+y for x, y in zip(list1, list2)]
end = t.time()

print("Python list addition time : ",end-start)

Python list addition time :  26.90754532814026


In [2]:
#numpy
import numpy as np
import time as t

size = 1_000_000_00

list1 = np.array(list(range(size)))
list2 = np.array(list(range(size)))

start = t.time()
sum = list1 + list2
end = t.time()

print("Python list addition time : ",end - start)

Python list addition time :  0.11332440376281738


In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.shape

(3, 3)

In [4]:
import sys
import numpy as np

list_array = list(range(10000))
numpy_array = np.array(list_array)

list_size = sys.getsizeof(list_array) * len(list_array)
print(list_size, "bytes")

nparray_size = numpy_array.nbytes
print(nparray_size, "bytes")

800560000 bytes
40000 bytes


In [15]:
import numpy as np
import time as t

st = t.time()
arr_list = list(range(1000000))
list_arr = [x**2 for x in arr_list]
et = t.time()

print("list op time : ",et-st)

list op time :  0.11199593544006348


In [16]:
import numpy as np
import time as t

st = t.time()
arr_list1 = np.array(list(range(1000000)))
np_array = arr_list1 ** 2
et = t.time()

print("Numpy list op time ",et-st)

Numpy list op time  0.07899737358093262


In [1]:
import numpy as np

arr = np.array([2,'sid'])
arr

array(['2', 'sid'], dtype='<U11')

In [2]:
arr.dtype


dtype('<U11')

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros(2)

array([0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.full(3,3)

array([3, 3, 3])

In [12]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [19]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [20]:
np.linspace(1,30,4)

array([ 1.        , 10.66666667, 20.33333333, 30.        ])

In [21]:
np.linspace(1,30,3)

array([ 1. , 15.5, 30. ])

In [22]:
import numpy as np

arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr1.shape

(2, 4)

In [24]:
arr1.dtype

dtype('int32')

In [26]:
arr1.astype('float32')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

In [27]:
arr1.astype('int64')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int64)

In [29]:
arr1.size

8

In [30]:
arr1.ndim

2

In [31]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [32]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
arr2.ndim

3

In [35]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [37]:
arr2.reshape(4,3,1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [38]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
arr2.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr2.reshape(0,4,3)

ValueError: cannot reshape array of size 12 into shape (0,4,3)

In [41]:
arr1.ndim

2

In [42]:
arr[1:2]

array([2])

In [43]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
arr1[0]

array([1, 2, 3, 4])

In [45]:
arr2[1:2]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr

array([1, 2, 3, 4, 5])

In [48]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
arr
arr1
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr2[0:1,0:1,:]

array([[[1, 2, 3]]])

In [51]:
arr2[:,:,1:2] = 0

In [52]:
arr2

array([[[ 1,  0,  3],
        [ 4,  0,  6]],

       [[ 7,  0,  9],
        [10,  0, 12]]])

In [59]:
nw_arr = arr2[:,:,1:2] #[depth,rows,cols]
nw_arr

array([[[3],
        [3]],

       [[3],
        [3]]])

In [60]:
nw_arr[:,:,0:1]=3


In [61]:
arr2

array([[[ 1,  3,  3],
        [ 4,  3,  6]],

       [[ 7,  3,  9],
        [10,  3, 12]]])

In [62]:
arr2[arr2>3]

array([ 4,  6,  7,  9, 10, 12])

In [63]:
arrr = arr2.copy()

In [64]:
arrr

array([[[ 1,  3,  3],
        [ 4,  3,  6]],

       [[ 7,  3,  9],
        [10,  3, 12]]])

In [68]:
arr2[[0]]

array([[[1, 3, 3],
        [4, 3, 6]]])

In [69]:
arr2[1]

array([[ 7,  3,  9],
       [10,  3, 12]])

In [70]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
print(np.sum(arr3,axis=0))

[[ 8 10 12]
 [14 16 18]]


In [74]:
arr3+arr2  #broadcasting : performing comlex operation without using extra memory

array([[[ 2,  5,  6],
        [ 8,  8, 12]],

       [[14, 11, 18],
        [20, 14, 24]]])

In [75]:
np.mean(arr3)

6.5

In [76]:
np.std(arr3)

3.452052529534663

In [77]:
np.var(arr3)

11.916666666666666

In [78]:
np.sum(arr3)

78

In [79]:
np.prod(arr3)

479001600

In [80]:
np.unique(arr3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])